# Generated by Django 3.1.7 on 2021-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='finalizado',
            field=models.BooleanField(verbose_name='Já finalizado'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='resenha',
            field=models.TextField(blank=True, null=True, verbose_name='Resenha'),
        ),
    ]
